set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports cout]
set_property LOAD 5 [get_ports {sum[0]}]
set_property LOAD 5 [get_ports {sum[10]}]
set_property LOAD 5 [get_ports {sum[11]}]
set_property LOAD 5 [get_ports {sum[12]}]
set_property LOAD 5 [get_ports {sum[13]}]
set_property LOAD 5 [get_ports {sum[14]}]
set_property LOAD 5 [get_ports {sum[15]}]
set_property LOAD 5 [get_ports {sum[1]}]
set_property LOAD 5 [get_ports {sum[2]}]
set_property LOAD 5 [get_ports {sum[3]}]
set_property LOAD 5 [get_ports {sum[4]}]
set_property LOAD 5 [get_ports {sum[5]}]
set_property LOAD 5 [get_ports {sum[6]}]
set_property LOAD 5 [get_ports {sum[7]}]
set_property LOAD 5 [get_ports {sum[8]}]
set_property LOAD 5 [get_ports {sum[9]}]
